### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Pantyhose-X** [zeuner/edutest-chatcommands#6]
F:\TW\minetest-5.5.0-win64\bin\..\mods\edutest_chatcommands\init.lua:
...st-5.5.0-win64\bin\..\mods\edutest_chatcommands\init.lua:231: unexpected symbol near '='

**Comment by zeuner** [comment]
Thanks for reporting. I can't reproduce it, though. What Lua version does your Minetest build use?

**Comment by Pantyhose-X** [comment]
> Thanks for reporting. I can't reproduce it, though. What Lua version does your Minetest build use?

Sorry, I reinstalled the mods and it no longer gives errors
